-- Fix permissive RLS policies flagged by linter

-- 1) Notifications: prevent arbitrary inserts; notifications for messages are generated by trigger
DROP POLICY IF EXISTS "System can insert notifications" ON public.notifications;
CREATE POLICY "Users can insert own notifications"
ON public.notifications
FOR INSERT
WITH CHECK (auth.uid() = user_id);

-- 2) Create notifications automatically when a private message is sent
CREATE OR REPLACE FUNCTION public.notify_on_private_message()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
SET row_security TO off
AS $$
BEGIN
  INSERT INTO public.notifications (user_id, type, title, message, link)
  VALUES (
    NEW.receiver_id,
    'new_message',
    'Новое сообщение',
    'У вас новое сообщение',
    '/messages/' || NEW.sender_id
  );

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_notify_on_private_message ON public.private_messages;
CREATE TRIGGER trg_notify_on_private_message
AFTER INSERT ON public.private_messages
FOR EACH ROW
EXECUTE FUNCTION public.notify_on_private_message();

-- 3) Rate limits: avoid USING/WITH CHECK = true while keeping anonymous access working
DROP POLICY IF EXISTS "Rate limits insert via function" ON public.rate_limits;
DROP POLICY IF EXISTS "Rate limits update via function" ON public.rate_limits;

CREATE POLICY "Rate limits insert guarded"
ON public.rate_limits
FOR INSERT
WITH CHECK (
  identifier IS NOT NULL
  AND length(identifier) > 0
  AND action_type IS NOT NULL
  AND length(action_type) > 0
);

CREATE POLICY "Rate limits update guarded"
ON public.rate_limits
FOR UPDATE
USING (
  identifier IS NOT NULL
  AND length(identifier) > 0
  AND action_type IS NOT NULL
  AND length(action_type) > 0
);
